defaults:
  - paths: default
  - sam: tiny
  - new_objects_fct:  automask #farthest_point #sampling_cc
  - _self_

# needs to be provided
recording: umbrella2

# Input/Output Paths  
source_folder: ${paths.data_dir}zed/${recording}
images_folder: ${paths.data_dir}zed/${recording}/images_undistorted_crop
masks_output_folder: ${paths.data_dir}/zed/${recording}/masks_${stride}_${max_frames}
mask_images_output_folder: ${paths.data_dir}/zed/${recording}/mask_images_${stride}_${max_frames} 
output_folder: ${paths.output_dir}
intrinsics_file: ${images_folder}/intrinsics.txt
obj_points_dir: ${source_folder}/obj_points_history

use_obj_points: true
# hardcoded for now

# Frame configs
subsample: 5 # subsample factor on original frames
chunk_size: 10 # chunk size of overlapping subsets
overlap: 1 # overlap between chunks

# Prompt with masks
prompt_with_masks: true

viz: false # visualize the first segmentation

# rerun viz specific
max_frames: 0  # Max frames to process, 0=no limit (default: 0)
headless: false
accumulate_points: true
