defaults:
  - paths: default
  - sam: tiny
  - new_objects_fct: automask
  - _self_

# needs to be provided
recording: office4

# Input/Output Paths  
source_folder: ${paths.data_dir}zed/${recording}
images_folder: ${paths.data_dir}zed/${recording}/images_undistorted_crop
masks_output_folder: ${paths.data_dir}/zed/${recording}/masks_${stride}_${max_frames}
mask_images_output_folder: ${paths.data_dir}/zed/${recording}/mask_images_${stride}_${max_frames} 
output_folder: ${paths.output_dir}
intrinsics_file: ${images_folder}/intrinsics.txt
obj_points_dir: ${source_folder}/obj_points_history

# Depth source configuration
depth_source: moge_aligned  # Options: "sensor" (default ZED depth), "moge" (MoGe-2 predicted depth), or "moge_aligned" (MoGe-2 aligned with sensor)
moge_depth_dir: ${paths.data_dir}zed/${recording}/moge_depths  # Path to MoGe-2 depth maps
moge_aligned_depth_dir: ${paths.data_dir}zed/${recording}/moge_aligned_depths  # Path to aligned MoGe-2 depth maps

use_obj_points: true
# hardcoded for now

# Frame configs
subsample: 10 # subsample factor on original frames
chunk_size: 10 # chunk size of overlapping subsets
overlap: 1 # overlap between chunks

# Prompt with masks
prompt_with_masks: true

viz: false # visualize the first segmentation

# rerun viz specific
max_frames: 0  # Max frames to process, 0=no limit (default: 0)
headless: false
accumulate_points: true
use_tsdf: false  # Use TSDF volume representation instead of point clouds
