defaults:
  - paths: default
  - sam: tiny
  - _self_

# needs to be provided
recording: cooking

# Input/Output Paths  
source_folder: ${paths.data_dir}zed/${recording}/images_minimal
masks_output_folder: ${paths.data_dir}/zed/${recording}/masks_${stride}_${max_frames}
mask_images_output_folder: ${paths.data_dir}/zed/${recording}/mask_images_${stride}_${max_frames} 
output_folder: ${paths.output_dir}

# Frame Processing
# stride: 5  # Select every Nth frame (default: 1)
max_frames: 100  # Max frames to process, 0=no limit (default: 0)

# SAM2 Model Configuration
device: "auto"  # "cuda", "cpu", or "auto" (default: "auto")

# Processing Options
jpeg_quality: 100  # JPEG quality 1-100 (default: 95)
cleanup_temp: true  # Remove temp files after processing (default: true)

chunk_size: 5
overlap: 1
subsample: 4 

viz: false

mask_buffer_radius: 10
num_points: 5