defaults:
  - paths: default
  - _self_

recording: office1

source_folder: ${paths.data_dir}zed/${recording}
images_folder: ${paths.data_dir}zed/${recording}/images_undistorted_crop
masks_output_folder: ${paths.data_dir}/zed/${recording}/masks_${stride}_${max_frames}

